name: CI

on:
  pull_request:
    branches:
      - develop
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore Opcion1LosChambos/Opcion1LosChambosApp/LosChambos.csproj

    - name: Build
      run: dotnet build Opcion1LosChambos/Opcion1LosChambosApp/LosChambos.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test Opcion1LosChambos/Opcion1LosChambosTest/Opcion1LosChambosTest.csproj --no-build --verbosity normal
